force-app/main/default/objects/Beer__c/Beer__c.object-meta.xml
<CustomObject>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Beer__c/fields/coder_Tags__c.field-meta.xml
<CustomField>
    <fullName>coder_Tags__c</fullName>
    <label>coder Tags</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Beer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BeerArchiveBatch.cls
public with sharing class BeerArchiveBatch implements Database.Batchable<SObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id, Status__c FROM Beer__c WHERE coder_Tags__c = \'Archive\' AND Status__c != \'Archive\''
        );
    }

    public void execute(Database.BatchableContext bc, List<Beer__c> scope) {
        for (Beer__c beer : scope) {
            beer.Status__c = 'Archive';
        }
        update scope;
    }

    public void finish(Database.BatchableContext bc) {
    }

}